version: '3'

services:
  main-app:
    build: .
    image: main-app
    environment:
      - MONGODB_URL=mongodb://mongodb:27017/tugasku
      - JWT_SECRET=eWueToyjw8oQuEN4SvDmiyXEfUvYZy9Fi5p4Uk5NdbUqpdweiFAtdmfvxcEz93MwzMDyhoDufNQue6FZgjADNp6PLFgVMe2MF4dqE5XNFA7DqGZuAiz3f5zvudSynvuo
      - JWT_ACCESS_EXPIRATION_MINUTES=30
      - JWT_REFRESH_EXPIRATION_DAYS=30
      - JWT_RESET_PASSWORD_EXPIRATION_MINUTES=10
      - JWT_VERIFY_EMAIL_EXPIRATION_MINUTES=10
    ports:
      - '3000:3000'
    depends_on:
      - mongodb
    volumes:
      - .:/usr/src/main-app
    networks:
      - main-network
  
  mongodb:
    image: mongo:4.2.1-bionic
    ports:
      - '27017:27017'
    volumes:
      - dbdata:/data/db
    networks:
      - main-network

volumes:
  dbdata:

networks:
  node-network:
    driver: bridge  